//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prodagi
    {
        public int IDProdagi { get; set; }
        public int IDList { get; set; }
        public int IDUser { get; set; }
        public int IDTovar { get; set; }
        public System.DateTime DataProdagi { get; set; }
        public decimal ProductPrice { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual Tovar Tovar { get; set; }
        public virtual User User { get; set; }
      
    }
}
