//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.Prodagi = new HashSet<Prodagi>();
        }
    
        public int IDTovar { get; set; }
        public int IDPostavshika { get; set; }
        public string TovarName { get; set; }
        public string PurchasePrice { get; set; }
        public string SalePrice { get; set; }
        public int Quantity { get; set; }
        public string Recipe { get; set; }
        public System.DateTime BestBeforeDate { get; set; }
        public int IDVid { get; set; }
    
        public virtual Postavshik Postavshik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prodagi> Prodagi { get; set; }
        public virtual Vid Vid { get; set; }
    }
}
